public_key: 'demopublickey'
private_key: 'demoprivatekey'
upload_url_base: 'https://upload.staging0.uploadcare.com'
api_url_base: 'https://api.staging0.uploadcare.com'
static_url_base: 'https://staging0.ucarecdn.com'
api_version: '0.2'
